#ifndef _QUECTEL_DEMO_CONFIG_H_
#define _QUECTEL_DEMO_CONFIG_H_
#define CFG_ENABLE_QUECTEL_UART   0
#define CFG_ENABLE_QUECTEL_I2C1   0
#define CFG_ENABLE_QUECTEL_TIMER  0
#define CFG_ENABLE_QUECTEL_SPI    0
#define CFG_ENABLE_QUECTEL_SPI_FLASH  0
#define CFG_ENABLE_QUECTEL_PWM     0
#define CFG_ENABLE_QUECTEL_GPIO   0
#define CFG_ENABLE_QUECTEL_FLASH  0
#define CFG_ENABLE_QUECTEL_ADC    0
#define CFG_ENABLE_QUECTEL_BLE_PERIPHERA  0
#define CFG_ENABLE_QUECTEL_BLE_CENTRAL 0
#define CFG_ENABLE_QUECTEL_OSI      0
#define CFG_ENABLE_QUECTEL_LOWPOWER      0
#define CFG_ENABLE_QUECTEL_BLE_CONFIG_NETWORK      0
#define CFG_ENABLE_QUECTEL_WLAN_CONFIG_NETWORK      0
#define CFG_ENABLE_QUECTEL_W5500                   0

#if (CFG_ENABLE_QUECTEL_BLE_PERIPHERA == 1 && CFG_ENABLE_QUECTEL_BLE_CENTRAL == 1)
#error "no support"
#endif



#endif

