/*
 * [Warning!] This file is auto-generated by pika compiler.
 * Do not edit it manually.
 * The source code is *.pyi file.
 * More details: 
 * English Doc:
 * https://pikadoc.readthedocs.io/en/latest/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 * Chinese Doc:
 * https://pikadoc.readthedocs.io/zh/latest/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 */

#ifndef ___hashlib_Hash__H
#define ___hashlib_Hash__H
#include <stdio.h>
#include <stdlib.h>
#include "PikaObj.h"

PikaObj *New__hashlib_Hash(Args *args);

void _hashlib_Hash_copy(PikaObj *self);
Arg* _hashlib_Hash_digest(PikaObj *self);
char* _hashlib_Hash_hexdigest(PikaObj *self);
void _hashlib_Hash_new(PikaObj *self, char* mode, Arg* data);
void _hashlib_Hash_update(PikaObj *self, Arg* data);

#endif
