/*
 * [Warning!] This file is auto-generated by pika compiler.
 * Do not edit it manually.
 * The source code is *.pyi file.
 * More details: 
 * English Doc:
 * https://pikadoc.readthedocs.io/en/latest/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 * Chinese Doc:
 * https://pikadoc.readthedocs.io/zh/latest/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 */

#ifndef __base64__H
#define __base64__H
#include <stdio.h>
#include <stdlib.h>
#include "PikaObj.h"

PikaObj *New_base64(Args *args);

Arg* base64_b64decode(PikaObj *self, Arg* s);
Arg* base64_b64encode(PikaObj *self, Arg* s);

#endif
