/*
 * [Warning!] This file is auto-generated by pika compiler.
 * Do not edit it manually.
 * The source code is *.pyi file.
 * More details: 
 * English Doc:
 * https://pikadoc.readthedocs.io/en/latest/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 * Chinese Doc:
 * https://pikadoc.readthedocs.io/zh/latest/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 */

#include "PikaMain.h"
#include <stdio.h>
#include <stdlib.h>

volatile PikaObj *__pikaMain;
PikaObj *pikaScriptInit(void){
    __platform_printf("======[pikascript packages installed]======\r\n");
    pks_printVersion();
    __platform_printf("PikaStdDevice==v2.1.1\r\n");
    __platform_printf("PikaStdLib==v1.11.9\r\n");
    __platform_printf("===========================================\r\n");
    PikaObj* pikaMain = newRootObj("pikaMain", New_PikaMain);
    __pikaMain = pikaMain;
    extern unsigned char pikaModules_py_a[];
    obj_linkLibrary(pikaMain, pikaModules_py_a);
#if PIKA_INIT_STRING_ENABLE
    obj_run(pikaMain,
            "import PikaStdLib\n"
            "import PikaStdDevice as std\n"
            "import FC41D\n"
            "time = FC41D.Time()\n"
            "mem = PikaStdLib.MemChecker()\n"
            "print('hello pikascript on FC41D')\n"
            "print('mem.max :')\n"
            "mem.max()\n"
            "print('mem.now :')\n"
            "mem.now()\n"
            "G1 = std.GPIO()\n"
            "G1.setPin('22')\n"
            "G1.setMode('out')\n"
            "G1.enable()\n"
            "G1.low()\n"
            "G2 = std.GPIO()\n"
            "G2.setPin('23')\n"
            "G2.setMode('out')\n"
            "G2.enable()\n"
            "G2.low()\n"
            "while True:\n"
            "    mem.now()\n"
            "    G1.low()\n"
            "    G2.high()\n"
            "    time.sleep_ms(500)\n"
            "    G1.high()\n"
            "    G2.low()\n"
            "    time.sleep_ms(500)\n"
            "    \n"
            "\n");
#else 
    obj_runModule((PikaObj*)pikaMain, "main");
#endif
    return pikaMain;
}

